-- RBAC matrix for cd_web (source of truth: roles + role_permissions in DB).
-- Auto-sync on startup: RbacDataInitializer.alignSalesRole / alignWarehouseRole
--
-- Role IDs (typical): ADMIN=1, WAREHOUSE=2, SALES=3, CUSTOMER=4
--
-- SALES (8):
--   PRODUCT_VIEW, ORDER_VIEW_ALL, ORDER_CONFIRM, ORDER_CANCEL,
--   ORDER_ASSIGN_SHIPPING, ORDER_TRACKING_UPDATE, WARRANTY_MANAGE, REPORT_SALES
--
-- WAREHOUSE (11):
--   PRODUCT_VIEW, PRODUCT_CREATE, PRODUCT_UPDATE, STOCK_IMPORT, IMEI_MANAGE,
--   INVENTORY_STAT, ORDER_VIEW_ALL, ORDER_CANCEL, ORDER_ASSIGN_SHIPPING,
--   ORDER_TRACKING_UPDATE, WARRANTY_MANAGE
--
-- WAREHOUSE intentionally excludes:
--   ORDER_CONFIRM (Sales xác nhận đơn PENDING),
--   ORDER_MANAGE (bulk admin orders),
--   PRODUCT_MANAGE (coupon / full admin product),
--   STOCK_RETURN (trả hàng nhập kho)
